from django.urls import path
from .views import (
    AdminLoginView, AdminMarkDeliveredView, AdminOrderDetailView, AdminOrderListView, AdminOverviewAPIView, AdminProductNamesListView, AdminReviewDeleteView, AdminReviewDetailView, AdminReviewListView, AuctionDetailAdminView, AuctionUpdateView, 
    CategoryListCreateView, CategoryEditView, CategoryDeleteView, 
    AuctionListCreateView, CategoryToggleActiveView, 
    CoinPackageListCreateView, CoinPackageToggleActiveView, 
    CoinPackageEditView, DeleteAuctionView, EndAuctionView, 
    AdminUserManagementView, AdminUserAuctionHistoryView,
    AdminUserTransactionHistoryView, AdminUserDetailsView,
    AdminProfileUpdateView, AdminChangePasswordView,
    AdminMyselfView, CoinStatsView,
    RevenueAuctionsYearlyChartView, TopPerformanceAuctionsView, UserParticipationYearlyChartView, AdminUserSearchView,
    AdminSendAnnouncementView,AdminAnnouncementListView,AdminAnnouncementDeleteView,
)

app_name = "admin_api"

urlpatterns = [
    path('login/', AdminLoginView.as_view(), name='admin_login'),
    path('categories/', CategoryListCreateView.as_view(), name='category_list_create'),
    path('categories/edit/', CategoryEditView.as_view(), name='category_edit'),
    path('categories/toggle-active/', CategoryToggleActiveView.as_view(), name='category-toggle-active'),
    path('categories/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('auctions/', AuctionListCreateView.as_view(), name='auction_list_create'),
    path('coin-packages/', CoinPackageListCreateView.as_view(), name='coin_package_list_create'),
    path('coin-packages/toggle/', CoinPackageToggleActiveView.as_view(), name='coin_package_toggle'),
    path('coin-packages/edit/', CoinPackageEditView.as_view(), name='coin_package_edit'),
    path('auctions/detail/', AuctionDetailAdminView.as_view(), name='auction-detail-admin'),
    path('auctions/end/', EndAuctionView.as_view(), name='admin-end-auction'),
    path('auctions/delete/', DeleteAuctionView.as_view(), name='admin-delete-auction'),
    path('auctions/<int:pk>/update/', AuctionUpdateView.as_view(), name='auction-update'),
    path('users/', AdminUserManagementView.as_view(), name='admin_user_management'),
    path('users/toggle-status/', AdminUserManagementView.as_view(), name='admin_user_toggle_status'),
    path('users/history/', AdminUserAuctionHistoryView.as_view(), name='admin_user_auction_history'),
    path('users/transactions/', AdminUserTransactionHistoryView.as_view(), name='admin_user_transactions'),
    path('users/details/', AdminUserDetailsView.as_view(), name='admin_user_details'),
    path('profile/update/', AdminProfileUpdateView.as_view(), name='admin_profile_update'),
    path('profile/me/', AdminMyselfView.as_view(), name='admin_profile_me'),
    path('profile/change-password/', AdminChangePasswordView.as_view(), name='admin_change_password'),
    path('coin-stats/', CoinStatsView.as_view(), name='admin_coin_stats'),
    path('overview/', AdminOverviewAPIView.as_view(), name='admin-overview'),
    path('chart/revenue-auctions-yearly/', RevenueAuctionsYearlyChartView.as_view(), name='chart-revenue-auctions-yearly'),
    path('chart/user-participation-yearly/', UserParticipationYearlyChartView.as_view(), name='chart-user-participation-yearly'),
    path('top-auctions/', TopPerformanceAuctionsView.as_view(), name='top-performance-auctions'),
    path('orders/', AdminOrderListView.as_view(), name='admin-order-list'),
    path('orders/<int:order_id>/', AdminOrderDetailView.as_view(), name='admin-order-detail'),
    path('orders/<int:order_id>/mark-delivered/', AdminMarkDeliveredView.as_view(), name='admin-mark-delivered'),
    path('reviews/', AdminReviewListView.as_view(), name='admin-review-list'),
    path('reviews/<int:review_id>/', AdminReviewDetailView.as_view(), name='admin-review-detail'),
    path('products/names/', AdminProductNamesListView.as_view(), name='admin-product-names'),
    path('reviews/<int:review_id>/delete/', AdminReviewDeleteView.as_view(), name='admin-review-delete'),
    path('users/search/', AdminUserSearchView.as_view(), name='admin-user-search'),
    path('announcements/', AdminSendAnnouncementView.as_view(), name='admin-send-announcement'),
    path('announcements/list/', AdminAnnouncementListView.as_view(), name='admin-announcement-list'),
    path('announcements/<int:announcement_id>/delete/', AdminAnnouncementDeleteView.as_view(), name='admin-announcement-delete'),
]